/* GENERATED by tools/build-concierge-kb.mjs — do not edit by hand.
 *
 * The procedure comparison pages Dr. Leo may walk a visitor to. Derived from
 * the live database using the SAME threshold and the SAME verified-provider
 * population as getPricedProcedures(), which is what generateStaticParams()
 * uses — so he can never offer a page that 404s.
 *
 * Re-run the builder after any verification or price-collection pass.
 * Built 2026-09-07 from 26 priced procedures
 * (>= 3 verified clinics each).
 */
export type ConciergeProcedure = { slug: string; name: string; es: string | null }

export const PRICED_PROCEDURES: ConciergeProcedure[] = [
  {
    "slug": "dental-implant",
    "name": "Dental Implant",
    "es": "implantes dentales"
  },
  {
    "slug": "zirconia-crown",
    "name": "Zirconia Crown",
    "es": "coronas de zirconia"
  },
  {
    "slug": "porcelain-veneer",
    "name": "Porcelain Veneer",
    "es": "carillas de porcelana"
  },
  {
    "slug": "root-canal",
    "name": "Root Canal",
    "es": "endodoncia"
  },
  {
    "slug": "dental-cleaning",
    "name": "Dental Cleaning",
    "es": "limpieza dental"
  },
  {
    "slug": "teeth-whitening",
    "name": "Teeth Whitening",
    "es": "blanqueamiento dental"
  },
  {
    "slug": "composite-filling",
    "name": "Composite Filling",
    "es": "resinas dentales"
  },
  {
    "slug": "dentures",
    "name": "Dentures",
    "es": null
  },
  {
    "slug": "braces",
    "name": "Braces",
    "es": null
  },
  {
    "slug": "all-on-4",
    "name": "All-on-4 Implants",
    "es": "implantes All-on-4"
  },
  {
    "slug": "deep-cleaning",
    "name": "Deep Cleaning",
    "es": "limpieza profunda"
  },
  {
    "slug": "tooth-extraction",
    "name": "Tooth Extraction",
    "es": "extracción dental"
  },
  {
    "slug": "bone-graft",
    "name": "Bone Graft",
    "es": "injerto de hueso"
  },
  {
    "slug": "composite-veneer",
    "name": "Composite Veneer",
    "es": "carillas de resina"
  },
  {
    "slug": "consultation-exam",
    "name": "Consultation / Exam",
    "es": "consulta dental"
  },
  {
    "slug": "3-unit-bridge",
    "name": "3-Unit Dental Bridge",
    "es": "puente dental de tres piezas"
  },
  {
    "slug": "all-on-6",
    "name": "All-on-6 Implants",
    "es": "implantes All-on-6"
  },
  {
    "slug": "metal-porcelain-crown",
    "name": "Metal Porcelain Crown",
    "es": "coronas de porcelana con metal"
  },
  {
    "slug": "weight-loss-ozempic-wegovy",
    "name": "Weight Loss (Ozempic / Wegovy / Semaglutide)",
    "es": "medicamentos para bajar de peso"
  },
  {
    "slug": "wisdom-tooth-extraction",
    "name": "Wisdom Tooth Extraction",
    "es": "extracción de muelas del juicio"
  },
  {
    "slug": "crown-over-implant",
    "name": "Crown Over Implant",
    "es": "corona sobre implante"
  },
  {
    "slug": "emax-crown",
    "name": "E-Max Crown",
    "es": "coronas E-Max"
  },
  {
    "slug": "eye-exam",
    "name": "Eye Exam",
    "es": "examen de la vista"
  },
  {
    "slug": "cosmetic-consultation",
    "name": "Cosmetic Consultation",
    "es": "consulta estética"
  },
  {
    "slug": "lumineer",
    "name": "Lumineer",
    "es": null
  },
  {
    "slug": "respiratory-asthma",
    "name": "Respiratory / Asthma",
    "es": "medicamentos para el asma"
  }
]
